server:
  port: 8081

spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012