name: aptner server CI/CD

on:
  push:
    branches: [main]

env:
  S3_BUCKET_NAME: aptdeploy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./website

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Remove old configuration files
        run: |
          cd /home/runner/work/BE_Project/BE_Project/aptner/src/main/resources
          rm application.yml application-local.yml application-test.yml

      - name: Create new application.yml
        run: |
          cd /home/runner/work/BE_Project/BE_Project/aptner/src/main/resources
          touch application.yml
          echo "${{ secrets.APPLICATION }}" > application.yml
          cat application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x /home/runner/work/BE_Project/BE_Project/aptner/gradlew

      - name: Build with Gradle
        run: |
          cd aptner
          ./gradlew clean build

      # Create deployment directory and copy necessary files
      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp /home/runner/work/BE_Project/BE_Project/aptner/appspec.yml ./deploy
          cp /home/runner/work/BE_Project/BE_Project/aptner/deploy.sh ./deploy
          cp /home/runner/work/BE_Project/BE_Project/aptner/build/libs/*.jar ./deploy

      # Create zip file for deployment
      - name: Create deployment package
        run: zip -r ./aptnerapp.zip ./deploy
        shell: bash

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Upload deployment package to S3
      - name: Upload deployment package to S3
        run: aws s3 cp --region ap-northeast-2 ./aptnerapp.zip s3://$S3_BUCKET_NAME/

      # Deploy the application
      - name: Deploy to AWS
        run: |
          aws deploy create-deployment \
          --application-name aptner \
          --deployment-group-name aptnergr \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=aptdeploy,bundleType=zip,key=aptnerapp.zip \
          --region ap-northeast-2
